# Generated by Django 4.0.4 on 2022-06-21 12:45

from django.db import migrations, models
import tour.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('photo', models.ImageField(upload_to=tour.utils.upload_photo_to)),
                ('is_restored', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to=tour.utils.upload_video_to)),
                ('video_vr', models.FileField(blank=True, null=True, upload_to=tour.utils.upload_video_to)),
                ('virtual_tour', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
